version: "3"
services:
  arya:
    image: "ajeep/arya:test"
    build:
      context: ./
      dockerfile: arya.Dockerfile
    restart: unless-stopped
    ports:
      - "8170:8080"
        #env_file: ./docker/fqdn.env
        #entrypoint: /mnt/openssl/create.sh
        #command: ["nginx", "-g", "daemon off;"]
